### ISSUE TITLE
It doesn't work on firefox 26

### ISSUE THREAD

**Issue by brucmao** [albancrommer/skiptco#1]
It doesn't work on firefox 26,please check it

**Comment by albancrommer** [comment]
Sorry missed the issue...

Yes, that is possible. the plugin should be reworked for FF so that it might be compliant with tweetdeck.

**Comment by rugk** [comment]
Haha, you reply to this issue _now_?

I mean I can confirm it works with FF 49.0.1, but I have no plans to test it with FF 26. :laughing:

**Comment by albancrommer** [comment]
Well, since it keeps working in FF, we'll close the issue. Checked in FF 49 and twitter.
