### ISSUE TITLE
WebExtensions are the future

### ISSUE THREAD

**Issue by rugk** [albancrommer/skiptco#10]
The current plan is that Firefox 57 will only support [web extensions](https://wiki.mozilla.org/WebExtensions). Your add-on is not a web extension yet as far as I can see, so you should consider remaking your add-on. The Firefox 57 release is [planned for 28th November 2017](https://wiki.mozilla.org/RapidRelease/Calendar).
Already for Firefox 53 (planned release: 18th April 2017) it is planned to no longer accept other new add-on submissions than web extensions on AMO (addons.mozilla.org). Old extensions can however still be updated.
The good message is that one should be able to use your web extensions add-on in all mayor browsers. That's the idea behind web extensions.
Note that you can use so-called [hybrid extensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) for switching to WebExtensions.

Note that all dates are estimates and may be changed.

German source: https://www.soeren-hentzschel.at/firefox/firefox-57-mit-exklusiver-webextension-unterstuetzung/
Original source: https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/

----

Also note that https://github.com/albancrommer/skiptco/issues/5 also is not really closed as at least [ACR](https://addons.mozilla.org/de/firefox/addon/add-on-compatibility-reporter/) still shows that this add-on is not compatible with e10s.

**Comment by rugk** [comment]
BTW I got the tip to look at [this addon](https://addons.mozilla.org/de/firefox/addon/another-twitter-link-expander/) (source here: https://github.com/gcp/twitter-link-expander).

**Comment by rugk** [comment]
You can [archive this repository](https://help.github.com/articles/archiving-repositories/), to mark it as unmaintained. People then cannot submit PRs and there is a big warning that this is archived.
Remember to add a note to the Readme before to explain that it is unmaintained, and – if you think this is useful – why and probably mention alternatives.

**Comment by albancrommer** [comment]
Thanks for that info. 

For now I won't lock the project. 

But it's certain I don't have time to convert it to WebExtension, as far as I can tell.
