### ISSUE TITLE
T.co link still in adress on hover

### ISSUE THREAD

**Issue by rugk** [albancrommer/skiptco#12]
On Twitter all links are still t.co links when I hover on them.

**Comment by rugk** [comment]
Okay maybe it really only is the "popup"/address hover (on the left bottom) shown in Firefox…

**Comment by rugk** [comment]
Hmm? Closing without comment? What's up?

**Comment by albancrommer** [comment]
Well sorry, these issues were old and I couldn't confirm they were important to anyone now. 

To be honest, I didn't have email notifications so I didn't even see that issue. 

Do you have a screenshot ?

**Comment by rugk** [comment]
well… no, it's a valid reaosn to close a ticket, just would be good to make a note of why you close it, so I'm not so stupid asking this.

Given this is an old add-on I cannot test it.
