### ISSUE TITLE
Faster, more thorough

### ISSUE THREAD

**Issue by GarrettS** [albancrommer/skiptco#2]
There is another category of t.co link that is missed by this plugin. I've addressed that type in my bookmarklet: "data-original-title"

Where that fails, there is always the option to parse the element's `textContent`, which in most cases, will be the actual URL.

https://gist.github.com/GarrettS/78fa75be89a584ee59f2

Also, it might be more efficient to use mouseover and not continually trawl the DOM.

**Comment by albancrommer** [comment]
Sorry, missed the issue...

I'll have a look at missed elements. 

Regarding mouseover, and efficiency, I'd like to look at the numbers and responsiveness. My first tests weren't so good, but I might have missed something.

**Comment by albancrommer** [comment]
While I can understand the interest for a "hovering" solution, I still consider it a less efficient solution on the long run. 

Not closing the door to this as an option, I'll probably tweak a script version for that.
