### ISSUE TITLE
URLs in IFRAMEs

### ISSUE THREAD

**Issue by GarrettS** [albancrommer/skiptco#3]
Media URLs aren't run through skiptco but they should be.

These links are in IFRAMEs which is why skiptco can't expand them. 

There should be a workaround for this but I don't know what it is,

**Comment by albancrommer** [comment]
Sorry, missed that issue. 

Very good point. I don't know why it's not working, probably a basic DOM parsing issue. Will have a look.

**Comment by albancrommer** [comment]
The fix is ready for Chrome in version 1.2.2
