### ISSUE TITLE
Not compatible with e10s

### ISSUE THREAD

**Issue by rugk** [albancrommer/skiptco#5]
Is this add-on compatible with Electrolysis (e10s)? Electrolysis is the new architecture of Firefox and Mozilla already rolls out some stable Firefox versions with e10s enabled.

More information:
- https://arewee10syet.com/
- https://wiki.mozilla.org/Electrolysis

---

According to [ACL](https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/) this add-on is not compatible with e10s.

**Comment by albancrommer** [comment]
Good question. I've stopped using FF to access twitter, plus the FF plugin architecture was making development extra hard compared to chromium. 

Given the new architecture I worked out, that works for twitter & tweetdeck, I should have a look at building again for FF. Hope it's better now than the mess it was.

**Comment by rugk** [comment]
> FF plugin architecture was making development extra hard compared to chromium. 

You might be interested in [WebExtensions](https://wiki.mozilla.org/WebExtensions), an emerging standard which tries to standardize the add-on architecture/APIs through different browsers. An add-on using WebExtensions is also automatically compatible with e10s.

**Comment by albancrommer** [comment]
The new FF version > 50 is now available.
