### ISSUE TITLE
Possible as a Userscript (Greasemonkey)?

### ISSUE THREAD

**Issue by rugk** [albancrommer/skiptco#6]
Is it possible to port this add-on into a userscript?

If so could you create one and e.g. publish it on https://openuserjs.org/?

**Comment by albancrommer** [comment]
Probably. After all, it started like that, yet unpublished. 

I don't consider that a priority, but if I find time to solve the current issues, I'll have a look at extracting it this way.

**Comment by rugk** [comment]
FYI I've also asked another dev: https://github.com/johnpbloch/De-T-Co/issues/6

**Comment by albancrommer** [comment]
It was fairly easy. Please see the following script. Tested in Console for FF and Chromium.

https://github.com/albancrommer/skiptco/blob/master/greasemonkey/skiptco.js

**Comment by rugk** [comment]
Nice, when you now add the header (the comment block used by user scripts) you can upload it to a userscript host.

**Comment by albancrommer** [comment]
Done! See https://openuserjs.org/scripts/openuserjsalbancrommer.com/Skiptco

I'll need to add a reference to that in the documentation, keeping this issue open meanwhile

**Comment by rugk** [comment]
Nice, I'll try it out. It has all features of the add-on?

**Comment by albancrommer** [comment]
It's exactly the same DOM operational code.

**Comment by rugk** [comment]
Nice, that works indeed. And now you can also see the advantages of a simple userscript: it is restartless and it is cross-browser-compatible.
