### ISSUE TITLE
Breaks list mention links

### ISSUE THREAD

**Issue by rugk** [albancrommer/skiptco#9]
When you receive the "**user** has added you to **user/mylist**" notification the last link (user/mylist) is broken and actually links to `http://@user/mylist`.

---

Originally reported at https://github.com/johnpbloch/De-T-Co/issues/5, but now I see that it is this addon/userscript (currently I use the latter) is what causes this issue.

**Comment by albancrommer** [comment]
Interesting. I guess you observed this on twitter and not tweetdeck?

**Comment by rugk** [comment]
Yes.

**Comment by albancrommer** [comment]
@rugk can you please confirm it works ? Updating the open js now

**Comment by rugk** [comment]
This thing is not called "open js", but ["userscript"](https://openuserjs.org/about/Userscript-Beginners-HOWTO) (as there are also [other hosters](https://wiki.greasespot.net/User_Script_Hosting) and one could theoretically also install it from GitHub).

And no, for some reason, it does not work. :worried: (v 2.0.2)

**Comment by albancrommer** [comment]
Sorry, userscript :)

Updated to 2.0.3, should work now, sorry for the mistake.

**Comment by rugk** [comment]
If I would find the list mention right now, I could even test it. Nevermind, I'll tell you if some spammers add me to a new list. :wink:

**Comment by albancrommer** [comment]
@rugk juste tell me your twitter account; mine's Alban_C ;)

I'll add you to my new list : "Skiptco users" ;)

**Comment by rugk** [comment]
`@rugkme`

> I'll add you to my new list : "Skiptco users" ;)

Oh, how gorgeous. :laughing:

**Comment by rugk** [comment]
Unfortunately the latest version again has bug https://github.com/albancrommer/skiptco/issues/7. (cards are not expanded)
